### ISSUE TITLE
Uploading image file to 'picture:views' of existing document via API

### ISSUE THREAD

**Issue by RobertoPrimo** [nuxeo/doc.nuxeo.com#62]
Could you please tell me is it possible (and how) to add a new image file to an existing picture document as part of the 'picture:views' property in Nuxeo Platform?

My use case is the following, I can upload a picture file to the platform and after some time I would like to upload via API a file containing the same picture, but in a different size or mime-type. In this case, Nuxeo should treat the uploaded file only as a conversion of the existing image and not a new asset.

I have gone through the documentation of Nuxeo but cannot seem to find the answer to my question.

**Comment by efge** [comment]
These issues are about the documentation site itself, not working with Nuxeo. Please take your question to https://answers.nuxeo.com
