### ISSUE TITLE
checkpoint_segments deprecated since PostgreSQL 9.4

### ISSUE THREAD

**Issue by sviscapi** [nuxeo/doc.nuxeo.com#84]
Dear all,

I believe some parts of the documentation about PostgreSQL optimizations are outdated:

doc.nuxeo.com/nxdoc/1010/postgresql/

> wal_buffers = 16MB
checkpoint_segments = 32
checkpoint_completion_target=0.8

https://answers.nuxeo.com/general/q/12bdcecbe43d45b7a4c36c8124012b06/PostgreSQL-11-configuration-checkpoint_segments-32

If I understand correctly, "checkpoint_segments" are deprecated since PostgreSQL 9.4.

Best regards,

Samuel

**Comment by gcarlin** [comment]
Hello @sviscapi,

Please click on the button "Give feedback" on the related documentation page, or click on the pencil button on the top of the page and edit the current documentation page (a PR will be created in the doc repo). That's a better way to handle changes on the doc :)

**Comment by sviscapi** [comment]
Hi @gcarlin ,

Done, just submitted some feedback at the bottom of the documentation page.

Please keep me posted at https://answers.nuxeo.com/general/q/12bdcecbe43d45b7a4c36c8124012b06/PostgreSQL-11-configuration-checkpoint_segments-32

Cheers, Samuel
